### ISSUE TITLE
Python Django Projects

### ISSUE THREAD

**Issue by labesoft** [labesoft/django-projects#1]
Learning the concept of Python and Django is a great experience. But only theoretical learning is not enough. It is very important to implement our theoretical knowledge on some real-time projects and for that, you need project ideas.

There is no better way to learn Django or any other framework than by working on some real-world projects. Projects are essential to make learning easy for us. These projects will help you gain real-world experience and make you job-ready.

We are managing the scope of this project:

- [x] #2 Create a Calorie Calculator
- [x] #3 Create a Discussion forum
- [x] #4 Create a News Aggregator 
- [x] #5 Create an Online Job Portal
